### PR TITLE
Fix `starknet_simulateTransactions` wrongly named field

### LINKED ISSUE #1191: [bug] `starknet_simulateTransactions` returns a wrongly named field
Sending a request with `starknet_simulateTransactions` and one transaction returns:
```
{"jsonrpc":"2.0","result":[{"transaction_trace":{"validate_invocation":{"contract_address":"0x228e94f8e0027c4b1aa839f38ab7ad1f00bc2b2db20d9d4374238862b10bc10",
...
"fee_estimate":{"gas_consumed":"0x9bd","gas_price":"0x3b9aca0a","overall_fee":"0x24472618362"}}],"id":0}  
```

instead of `fee_estimation` as in [specs](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_trace_api_openrpc.json#L102).

### PR DESCRIPTION
**Pull request by tomek0123456789**
Closes #1191

### CODE REVIEW

File: rpc/simulation.go [hunk 1]
```diff
@@ -29,7 +29,7 @@ func (s *SimulationFlag) UnmarshalJSON(bytes []byte) (err error) {
 
 type SimulatedTransaction struct {
 	TransactionTrace json.RawMessage `json:"transaction_trace,omitempty"`
-	FeeEstimate      FeeEstimate     `json:"fee_estimate,omitempty"`
+	FeeEstimate      FeeEstimate     `json:"fee_estimation,omitempty"`
```
Comment (kirugan) [inline rpc/simulation.go:32]: Thanks for the fix 👍 don't you mind to rename `FeeEstmate` field into `FeeEstimation` also? no need to rename `FeeEstimate` type, just name of the field.

**Review by joshklop — APPROVED** [review]
