### PR TITLE
[sync] solve error around starting block Number

### LINKED ISSUE #361: Sync returning 0 on starknet_blockNumber before first iteration
**Describe the bug**
When the server starts, the `starknet_blockNumber` RPC returns 0 while the first block isn’t synched, including the case when I’m restarting the sync from a block > 0. We need to update this value before starting the sync.

**Expected behavior**
Return the real value that we have already synced.

### PR DESCRIPTION
**Pull request by stdevMac**
Resolves #361 

## Description

Solve the problem that exists around the initial block fetched.

## Changes:

- Set as default that the minimum block synced and the current block synced, both are the minimum between the block and the state processed.
- Fix Syncing response on Sync

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Testing

**Requires testing**: No

**Did you write tests??**: No

### CODE REVIEW

File: internal/sync/utils.go [hunk 1]
```diff
@@ -64,6 +64,7 @@ func loadAbiOfContract(abiVal string) (abi.ABI, error) {
 func fetchContractCode(stateDiff *types.StateDiff, client *feeder.Client, logger *zap.SugaredLogger) *CollectorDiff {
 	collectedDiff := &CollectorDiff{
 		stateDiff: stateDiff,
+		Code:      map[string]*types.Contract{},
```
Comment (adriantpaez) [inline internal/sync/utils.go:67]: Is it possible to use `make` here and set the map size properly with `len` of `stateDiff.DeployedContracts`?

**Review by adriantpaez — CHANGES_REQUESTED** [review]

**Review by IronGauntlets — APPROVED** [review]

File: internal/sync/utils.go (hunk 1 above)
Comment (stdevMac) [reply internal/sync/utils.go]: Changed to make, good catch!

File: internal/sync/sync.go [hunk 2]
```diff
@@ -220,8 +231,12 @@ func (s *Synchronizer) GetStateDiff(blockNumber int64) *types.StateDiff {
 	return s.syncManager.GetStateDiff(blockNumber)
 }
 
-func (s *Synchronizer) GetStateDiffFromHash(blockHash string) *types.StateDiff {
-	return s.syncManager.GetStateDiffFromHash(blockHash)
+func (s *Synchronizer) GetStateDiffFromFelt(blockHash *felt.Felt) *types.StateDiff {
```
[the remark this answers is not in the document]
Comment (stdevMac) [reply internal/sync/sync.go]: Back to `FromHash`

**Review by joshklop — APPROVED** [review]
