### PR TITLE
fix: getBlockWithTx* fetch block header and txns separately

### LINKED ISSUE #3261: `starknet_getBlockWithTxHashes` and `starknet_getBlockWithTxs` don't need to load receipts
Both are using `blockByID` which loads all receipts while these endpoints don't need anything from the receipts.

https://github.com/NethermindEth/juno/blob/v0.15.10/rpc/v9/block.go#L244
https://github.com/NethermindEth/juno/blob/v0.15.10/rpc/v9/block.go#L322

### PR DESCRIPTION
**Pull request by brbrr**
fixes #3261

### CODE REVIEW

File: rpc/v8/block.go [hunk 1]
```diff
@@ -231,29 +242,40 @@ func (h *Handler) BlockWithReceipts(id *BlockID) (*BlockWithReceipts, *jsonrpc.E
...
 	return &BlockWithTxs{
 		Status:       status,
-		BlockHeader:  adaptBlockHeader(block.Header),
+		BlockHeader:  adaptBlockHeader(header),
 		Transactions: txs,
 	}, nil
 }
 
-func (h *Handler) blockStatus(id *BlockID, block *core.Block) (rpcv6.BlockStatus, *jsonrpc.Error) {
+func (h *Handler) blockStatus(id *BlockID, blockNumber uint64) (rpcv6.BlockStatus, *jsonrpc.Error) {
```
Comment (MaksymMalicki) [inline rpc/v8/block.go:278]: nice!

File: rpc/v10/block.go [hunk 2]
```diff
@@ -62,34 +62,45 @@ type BlockWithReceipts struct {
 // It follows the specification defined here:
 // https://github.com/starkware-libs/starknet-specs/blob/cce1563eff702c87590bad3a48382d2febf1f7d9/api/starknet_api_openrpc.json#L25
 func (h *Handler) BlockWithTxHashes(id *rpcv9.BlockID) (*BlockWithTxHashes, *jsonrpc.Error) {
-	block, rpcErr := h.blockByID(id)
+	header, rpcErr := h.blockHeaderByID(id)
```
Comment (MaksymMalicki) [inline rpc/v10/block.go:71]: question, this PR basically makes a trade-off of reducing fetched data size (get rid of unnecessary receipts field) for the tradeoff of doing 2 DB reads instead of 1 right?

File: rpc/v8/block.go [hunk 3]
```diff
@@ -168,24 +168,35 @@ type BlockWithReceipts struct {
 // It follows the specification defined here:
 // https://github.com/starkware-libs/starknet-specs/blob/a789ccc3432c57777beceaa53a34a7ae2f25fda0/api/starknet_api_openrpc.json#L11
 func (h *Handler) BlockWithTxHashes(id *BlockID) (*BlockWithTxHashes, *jsonrpc.Error) {
```
Comment (MaksymMalicki) [inline rpc/v8/block.go:170]: btw why don't we do it for v6 and v7 as well? very small refactor, and I don't think we have a concrete plan to deprecate those anytime soon

File: rpc/v10/helpers.go [hunk 4]
```diff
@@ -66,6 +66,30 @@ func (h *Handler) blockByID(blockID *rpcv9.BlockID) (*core.Block, *jsonrpc.Error
...
+		if err != nil {
+			if errors.Is(err, core.ErrPendingDataNotFound) {
+				return nil, rpccore.ErrBlockNotFound
+			}
+			return nil, rpccore.ErrInternal.CloneWithData(err)
+		}
+		txns := pending.GetTransactions()
+		return txns, nil
+	default:
+		txns, err := h.bcReader.TransactionsByBlockNumber(blockID.Number())
```
Comment (MaksymMalicki) [inline rpc/v10/helpers.go:83]: btw, I don't think we have this method anymore. Since we have the new typed buckets, we fetch the transactions by block number and index. I think this will require a new `helper` function, where we can pass the number of transactions from header

File: rpc/v8/block.go (hunk 3 above)
Comment (brbrr) [reply rpc/v8/block.go:170]: I'm not sure it worth it, and Rodrigo suggested against it: https://github.com/NethermindEth/juno/pull/3296#discussion_r2657671909

File: rpc/v10/block.go (hunk 2 above)
Comment (brbrr) [reply rpc/v10/block.go:71]: hm, from my understanding, blockByID does 3 DB reads (header, txns, receipts), where this PR makes only 2 DB reads. I'm not sure how indexed batches work (they're used in `blockByID`), and potentially we might be performing a single database operation, but still, we are pulling unnecessary receipt data, which I assume will incur some overhead anyway.

File: rpc/v10/helpers.go (hunk 4 above)
Comment (brbrr) [reply rpc/v10/helpers.go:83]: I think it's there, as I can find it locally and the CI is not complaining 🤷

File: blockchain/blockchain.go [hunk 5]
```diff
@@ -32,13 +32,16 @@ type Reader interface {
...
 	BlockNumberByHash(hash *felt.Felt) (uint64, error)
-
-	TransactionByHash(hash *felt.Felt) (transaction core.Transaction, err error)
-	TransactionByBlockNumberAndIndex(blockNumber, index uint64) (transaction core.Transaction, err error)
 	BlockNumberAndIndexByTxHash(
 		hash *felt.TransactionHash,
 	) (blockNumber uint64, index uint64, err error)
 
+	TransactionByHash(hash *felt.Felt) (transaction core.Transaction, err error)
+	TransactionByBlockNumberAndIndex(
```
Comment (MaksymMalicki) [inline blockchain/blockchain.go:40]: could we increase the codecov by adding some tests for this method?
