### PR TITLE
Fix on nil pointer after connection broken with the Feeder gateway

### LINKED ISSUE #376: Panic fetching Transactions Receipts on the feeder package
**Describe the bug**
Panic fetching from the feeder gateway.

**Expected behavior**
Not panic.

**Screenshots**
```
2022-08-28T04:09:59Z	INFO	apiCollector	sync/apiCollection.go:75	StateDiff collected	{"BlockNumber": 65290}
2022-08-28T04:10:03Z	INFO	feeder/feeder.go:62	Waiting to do again a request	{"Waiting:": 10}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x976b24]

goroutine 24 [running]:
github.com/NethermindEth/juno/pkg/feeder.NewClient.func1(0xe?, {0xdcdb20, 0xc00024dce0})
	/home/ubuntu/go/src/github.com/NethermindEth/juno/pkg/feeder/feeder.go:61 +0x84
github.com/NethermindEth/juno/pkg/feeder.(*Client).do(0xc00089baf8, 0xc913d0?, {0xb55640, 0xc0001e0b40})
	/home/ubuntu/go/src/github.com/NethermindEth/juno/pkg/feeder/feeder.go:163 +0xe5
github.com/NethermindEth/juno/pkg/feeder.Client.GetTransactionReceipt({0xc000263200, 0xc000263210, 0xc0000f8ab0, {0xc9a43e, 0xf}, {0x0, 0x0}, 0xc00007e150}, {0xc00099cb40, 0x41}, ...)
	/home/ubuntu/go/src/github.com/NethermindEth/juno/pkg/feeder/feeder.go:529 +0x3c5
github.com/NethermindEth/juno/internal/sync.(*Synchronizer).updateTransactionReceipts(0xc0000f8b40, {0x6, {0xc00099cb40, 0x41}, {0xc000142000, 0x1, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	/home/ubuntu/go/src/github.com/NethermindEth/juno/internal/sync/sync.go:370 +0xdf
github.com/NethermindEth/juno/internal/sync.(*Synchronizer).updateBlock(0xc0000f8b40, 0x0?)
	/home/ubuntu/go/src/github.com/NethermindEth/juno/internal/sync/sync.go:327 +0x2a5
github.com/NethermindEth/juno/internal/sync.(*Synchronizer).updateBlocks(...)
	/home/ubuntu/go/src/github.com/NethermindEth/juno/internal/sync/sync.go:294
github.com/NethermindEth/juno/internal/sync.(*Synchronizer).updateBlocksInfo(0xc0000f8b40)
	/home/ubuntu/go/src/github.com/NethermindEth/juno/internal/sync/sync.go:391 +0x9b
created by github.com/NethermindEth/juno/internal/sync.(*Synchronizer).Run
	/home/ubuntu/go/src/github.com/NethermindEth/juno/internal/sync/sync.go:111 +0x65
```

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Config**
```
{Verbosity:info RpcPort:6060 Metrics:false DatabasePath:/home/ubuntu/.config/juno Network:goerli EthNode:}
```

### PR DESCRIPTION
**Pull request by stdevMac**
Resolves #376 

## Description

After a connection was lost, a nil pointer error was thrown. With these changes, the nil pointer cause was deleted, and also changed the waiting iterator.

## Changes:

- Fix nil pointer error on logs after an error fetching from the feeder gateway
- Remove 10 times and check for requests to the feeder gateway, will be forever.

## Types of changes

_Leave only items that describe your changes, remove the rest. Remove this line too._

- Bugfix (non-breaking change which fixes an issue)

## Testing

**Requires testing**: No

**Did you write tests??**: No

## Documentation

**If this requires a documentation update, did you add one?** No

### CODE REVIEW

File: pkg/feeder/feeder.go [hunk 1]
```diff
@@ -55,11 +55,10 @@ func NewClient(baseURL, baseAPI string, client *HttpClient) *Client {
 	retryFuncForDoReq := func(req *http.Request, httpClient HttpClient) (*http.Response, error) {
 		var res *http.Response
 		wait := 5 * time.Second
-		for i := 0; i < 10; i++ {
+		for i := 0; ; i++ {
```
Comment (adriantpaez) [inline pkg/feeder/feeder.go:58]: Looks like `i` isn't more necessary

**Review by adriantpaez — CHANGES_REQUESTED** [review]

**Review by joshklop — APPROVED** [review]
LGTM. I second @adriantpaez suggested change above.

**Review by IronGauntlets — APPROVED** [review]

**Review by adriantpaez — APPROVED** [review]

**Review by tshakalekholoane — APPROVED** [review]
