### PR TITLE
fix: use correct gas limit for simulations with SKIP_FEE_CHARGE

### LINKED ISSUE #2922: Out of gas transaction with `SKIP_FEE_CHARGE`
The following simulation fails with:
```json
{"jsonrpc":"2.0","error":{"code":41,"message":"Transaction execution error","data":{"transaction_index":0,"execution_error":"Transaction ran out of gas during simulation even with MAX gas limit"}},"id":78}
```

even though it is simulated with `SKIP_FEE_CHARGE`

Example request 
```
curl --location <juno_kink>/v0_8
--header 'content-type: application/json' \
--data '{
    "id": 78,
    "jsonrpc": "2.0",
    "method": "starknet_simulateTransactions",
    "params": {
        "block_id": {
            "block_number": 1478909
        },
        "transactions": [
            {
                "type": "INVOKE",
                "sender_address": "0x4ee02b9a3b97601d221a87d15e45524670319f8edca2fc58975147bf695e1cf",
                "calldata": [
                    "0x16",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0xa",
                    "0x0",
                    "0x35e30",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0xa",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0xb",
                    "0x0",
                    "0x1da",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0xb",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0xf",
                    "0x0",
                    "0x129",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0xf",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0x10",
                    "0x0",
                    "0x1ad035239",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0x10",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0x24b",
                    "0x0",
                    "0x22138b410",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0x24b",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0x24c",
                    "0x0",
                    "0x1469a2c6393",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0x24c",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0x2ff08",
                    "0x0",
                    "0x3a63c444",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0x2ff08",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0x34126",
                    "0x0",
                    "0x397e150aa62",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0x34126",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x7",
                    "0x36b25",
                    "0x0",
                    "0x539b",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0xfff107e2403123c7df78d91728a7ee5cfd557aec0fa2d2bdc5891c286bbfff",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0x36b25",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0x469b656239972a2501f2f1cd71bf4e844d64b7cae6773aa84c702327c476e5b",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x8",
                    "0x80c",
                    "0x0",
                    "0xfa0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x2540be3ff",
                    "0x469b656239972a2501f2f1cd71bf4e844d64b7cae6773aa84c702327c476e5b",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0x80c",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff",
                    "0x469b656239972a2501f2f1cd71bf4e844d64b7cae6773aa84c702327c476e5b",
                    "0x3bc75403f0d735653dce6c92437af5f88d5a4b49c6ef582454a66d3a033d429",
                    "0x8",
                    "0xdf8",
                    "0x0",
                    "0x1e854541",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x0",
                    "0x2540be3ff",
                    "0x469b656239972a2501f2f1cd71bf4e844d64b7cae6773aa84c702327c476e5b",
                    "0x284134db6f39215e1d0a0a3dbd382fd7d28af6b3e3d5b77bba35c3a1d0da316",
                    "0x5",
                    "0xdf8",
                    "0x0",
                    "0x1",
                    "0xffffffffffffffffffffffffffffffff",
                    "0xffffffffffffffffffffffffffffffff"
                ],
                "version": "0x100000000000000000000000000000003",
                "signature": [],
                "nonce": "0x3f5",
                "resource_bounds": {
                    "l2_gas": {
                        "max_amount": "0x0",
                        "max_price_per_unit": "0x0"
                    },
                    "l1_gas": {
                        "max_amount": "0x0",
                        "max_price_per_unit": "0x0"
                    },
                    "l1_data_gas": {
                        "max_amount": "0x0",
                        "max_price_per_unit": "0x0"
                    }
                },
                "tip": "0x0",
                "paymaster_data": [],
                "nonce_data_availability_mode": "L1",
                "fee_data_availability_mode": "L1",
                "account_deployment_data": []
            }
        ],
        "simulation_flags": [
            "SKIP_VALIDATE",
            "SKIP_FEE_CHARGE"
        ]
    }
}'
```

### PR DESCRIPTION
**Pull request by wojciechos**
Fixes #2922

When simulation flag SKIP_FEE_CHARGE is set, use blockifier's default maximum gas limit instead of account balance-dependent limit. This prevents artificial gas limitations during transaction simulation when fee charging is disabled.

The fix ensures that:
- When charge_fee=true: Use balance-dependent gas limit (existing behavior)
- When charge_fee=false: Use blockifier's default limit for proper simulation

### CODE REVIEW

**Review by rodrigo-pino — APPROVED** [review]

File: vm/rust/src/execution.rs [hunk 1]
```diff
@@ -158,6 +158,16 @@ enum SimulationError {
     ExecutionError(ExecutionError),
 }
 
+/// Gets the default maximum Sierra gas limit from blockifier's versioned constants.
+fn get_default_max_sierra_gas_limit(block_context: &BlockContext) -> GasAmount {
+    let max_sierra_gas_limit = block_context
+        .versioned_constants()
+        .os_constants
+        .validate_max_sierra_gas
```
Comment (EgeCaner) [inline vm/rust/src/execution.rs]: Should we use `validate_max_sierra_gas` instead of `execute_max_sierra_gas`?

Comment (rodrodros) [reply vm/rust/src/execution.rs]: It should be execute. Good catch!
