### PR TITLE
fix(rpc/v6): extremely large `gas_consumed`

### LINKED ISSUE #2580: Extremely Large gas_consumed in starknet_estimateFee
The starknet_estimateFee method returns an abnormally large gas_consumed value (`0x2a8f0838f43abbce39ae7eddd70831e02d737c33c57b40cab97b744991bd3e7`), which is inconsistent with the expected fee calculation and the reported overall_fee.

**Example:** 
Sepolia - RPC v0_7
```{
    "method": "starknet_estimateFee",
    "params": [
        [
            {
                "type": "INVOKE",
                "version": "0x3",
                "nonce": "0xdae",
                "sender_address": "0x4e67d40c642effa3737e82fcae4b1b58a29b3b9f25897748051d294a4417964",
                "signature": [
                    "0x48520928c5299e58d5d24e9a462495cc7f022ab4af64c34dbf64a9368a54e77",
                    "0xdb41a233ee1139a2f0f223040468b5eb971aeb10509d815ffca5a2d50e155d"
                ],
                "calldata": [
                    "0x1",
                    "0x697673dbd3917a67694327eac2553ce60474574599e38fef04245f2984a0d27",
                    "0x3dbc508ba4afd040c8dc4ff8a61113a7bcaf5eae88a6ba27b3c50578b3587e3",
                    "0xa0",
                    "0x414e595f43414c4c4552",
                    "0x358df5ecfaf91748ed58ef25a5e396dba424c8c6a6d44b2420e8e23aab8eba7",
                    "0x2",
                    "0x0",
                    "0x67bd9441",
                    "0x1",
                    "0x48f644eada02dc8a522354478e96a40b5cfaf8cdc98ed79b685a7058bb1882c",
                    "0x3b5d4de313cae97f0f4f2036bc8f7edb05c82d434cbb2d67259173b2a72844b",
                    "0x10",
                    "0x4260574272f94df654927e3a31a209d79a468ed6bb431d2ec848d29ab9464d3",
                    "0x697673dbd3917a67694327eac2553ce60474574599e38fef04245f2984a0d27",
                    "0x50",
                    "0x4736c5ee2a2e0873081d96212c3fbb5de7661837e45e9a055db965c17054f67",
                    "0x2c9284ceb1a4199cf283aa5fb8851873d08734c3e2036402a9c8f0a17ffb9e1",
                    "0x8065ad3a39445e16b31cfa71bf8f16d4",
                    "0x6e5b667c3706ecfb2a45e408828d4f2",
                    "0x4",
                    "0x5",
                    "0x0",
                    "0x2",
                    "0x0",
                    "0x3",
                    "0x0",
                    "0x5",
                    "0x1",
                    "0x86",
                    "0x73657373696f6e2d746f6b656e",
                    "0x67c6c8a2",
                    "0x16fe6b778b399144c88206df65918e28749e85ba1702af47dc3378a6c32ce79",
                    "0x0",
                    "0x5ced0d4a47a56f00b1f09f6a2538a4bc6970189dd53013e11cc973a55db16fc",
                    "0x0",
                    "0x1",
                    "0x6f",
                    "0x1",
                    "0x4",
                    "0x16",
                    "0x68",
                    "0x74",
                    "0x74",
                    "0x70",
                    "0x73",
                    "0x3a",
                    "0x2f",
                    "0x2f",
                    "0x78",
                    "0x2e",
                    "0x63",
                    "0x61",
                    "0x72",
                    "0x74",
                    "0x72",
                    "0x69",
                    "0x64",
                    "0x67",
                    "0x65",
                    "0x2e",
                    "0x67",
                    "0x67",
                    "0x9d0aec9905466c9adf79584fa75fed3",
                    "0x20a97ec3f8efbc2aca0cf7cabb420b4a",
                    "0xbe42eaf45ad0ccaf07b996360c44599b",
                    "0x96b374e7809a563b97f530498cd99648",
                    "0x4a",
                    "0x2c",
                    "0x22",
                    "0x63",
                    "0x72",
                    "0x6f",
                    "0x73",
                    "0x73",
                    "0x4f",
                    "0x72",
                    "0x69",
                    "0x67",
                    "0x69",
                    "0x6e",
                    "0x22",
                    "0x3a",
                    "0x74",
                    "0x72",
                    "0x75",
                    "0x65",
                    "0x2c",
                    "0x22",
                    "0x74",
                    "0x6f",
                    "0x70",
                    "0x4f",
                    "0x72",
                    "0x69",
                    "0x67",
                    "0x69",
                    "0x6e",
                    "0x22",
                    "0x3a",
                    "0x22",
                    "0x68",
                    "0x74",
                    "0x74",
                    "0x70",
                    "0x73",
                    "0x3a",
                    "0x2f",
                    "0x2f",
                    "0x73",
                    "0x74",
                    "0x61",
                    "0x67",
                    "0x69",
                    "0x6e",
                    "0x67",
                    "0x2d",
                    "0x63",
                    "0x61",
                    "0x72",
                    "0x74",
                    "0x72",
                    "0x69",
                    "0x64",
                    "0x67",
                    "0x65",
                    "0x2e",
                    "0x62",
                    "0x6c",
                    "0x6f",
                    "0x62",
                    "0x61",
                    "0x72",
                    "0x65",
                    "0x6e",
                    "0x61",
                    "0x2e",
                    "0x78",
                    "0x79",
                    "0x7a",
                    "0x22",
                    "0x7d",
                    "0x1d",
                    "0x0",
                    "0xf19d1bc2b54069b2485a51dfc959cb2e",
                    "0x1db7ab79eaccc4640cde4b57d22021d9",
                    "0x66591bded9a00c9d34c27b674af18ce0",
                    "0x204a2b933444b2085a4a8fb8a1fe2495",
                    "0x0",
                    "0x0",
                    "0x36a186a7aeb910d3228410b3bfca7731d73a4a444fdd0eee1dff7c32366c40b",
                    "0x3b036561be2dfed1cd29ee8d4a2e4f1abe9d5f7d6591be6836209cabfc126f",
                    "0x70562ee74e6ab962e64e93e3eccf0574b05f3bb6c90dce7cd27a4b0e7959240",
                    "0x0",
                    "0x1e6a6f52e47fe42e024287b729bc47e58019fcc7e1cc8b141bb8d669b779b49",
                    "0x78bd0a9c5c4b3b9b2d732039a89be9938ee1212be26a9aef1970e0cc193d709",
                    "0x72925e91168b032f1a7569767b915d1012560377b097eb78895c6a7f1cddf49",
                    "0x1",
                    "0x5",
                    "0x19c7fb11ef4a1643339a376baa352737d64b2628b25b54b98b6661ee7228e68",
                    "0x57dbf188074290c9d59fc1f250367288b7b46497a07dc690c9e8c71c58b33a3",
                    "0x4bcf4875097c1a6102ef0fcfe19a73776ce9fa8a6a8464cc2175af32f14167e",
                    "0x7f37c810722c3a876821ad8e5eac034552d15c6285de9faf12f84aae15aa601",
                    "0x13d0dfde5992683f7c58b1469f597ff37755befa5231a3bcb5f64116741facb"
                ],
                "resource_bounds": {
                    "l1_gas": {
                        "max_amount": "0x2c6a",
                        "max_price_per_unit": "0x508fabe419478"
                    },
                    "l2_gas": {
                        "max_amount": "0x0",
                        "max_price_per_unit": "0x0"
                    }
                },
                "tip": "0x0",
                "paymaster_data": [],
                "account_deployment_data": [],
                "nonce_data_availability_mode": "L1",
                "fee_data_availability_mode": "L1"
            }
        ],
        [
            "SKIP_VALIDATE"
        ],
        {
            "block_number": 549691
        }
    ],
    "id": 0,
    "jsonrpc": "2.0"
}
```

**Response**
```
{
    "jsonrpc": "2.0",
    "result": [
        {
            "gas_consumed": "0x2a8f0838f43abbce39ae7eddd70831e02d737c33c57b40cab97b744991bd3e7", //wtf so huge?!
            "gas_price": "0x1ada8ea15dc28",
            "data_gas_consumed": "0x600",
            "data_gas_price": "0x3ccf1f58c6a7f",
            "overall_fee": "0x20f1dcc31dc72d18",
            "unit": "FRI"
        }
    ],
    "id": 0
}
```

**Actual Behavior:**
gas_consumed is unrealistically large, suggesting a bug in the fee estimation logic or VM execution (h.vm.Execute). The reported overall_fee doesn’t align with such a massive gas_consumed.

**Expected**

gas_consumed should be a reasonable value (e.g., ~0x139)

### PR DESCRIPTION
**Pull request by AnkushinDaniil**
Fixes #2580

No tests yet, waiting for #2592 

Refactored `simulateTransactions` in `v6` and `v7` in the same way as `v8`, added tests

### CODE REVIEW

**Review by rodrigo-pino — COMMENTED** [review]
Should this be applied to v7 and v8? The issue was given by rpc 07 originally

**Comment by AnkushinDaniil** [comment]
> Should this be applied to v7 and v8? The issue was given by rpc 07 originally

On my machine it only failed on V6. Could you please double check?

**Comment by wojciechos** [comment]
> On my machine it only failed on V6. Could you please double check?

Just checked, and indeed it happen only on v6 - looks like some other PR fixed that on v7

**Review by rodrigo-pino — APPROVED** [review]

File: rpc/v6/simulation.go [hunk 1]
```diff
@@ -72,78 +72,123 @@ func (h *Handler) simulateTransactions(id BlockID, transactions []BroadcastedTra
...
-			return nil, jsonrpc.Err(jsonrpc.InvalidParams, aErr.Error())
+			return nil, nil, nil, jsonrpc.Err(jsonrpc.InvalidParams, aErr.Error())
 		}
 
 		if paidFeeOnL1 != nil {
 			paidFeesOnL1 = append(paidFeesOnL1, paidFeeOnL1)
 		}
 
-		txns[idx] = txn
+		txns = append(txns, txn)
```
[the remark this answers is not in the document]
Comment (AnkushinDaniil) [reply rpc/v6/simulation.go]: [Add index iteration](https://github.com/NethermindEth/juno/pull/2602/commits/7e69bea713c42cf3144770fc690efb49c7c4dc0e)

File: rpc/v6/simulation.go [hunk 2]
```diff
@@ -92,58 +124,71 @@ func (h *Handler) simulateTransactions(id BlockID, transactions []BroadcastedTra
...
-			}
+		switch feeUnit {
+		case WEI:
+			l1GasPrice = l1GasPriceWei
+		case FRI:
+			l1GasPrice = l1GasPriceStrk
 		}
 
-		gasConsumed := overallFee.Clone()
-		gasConsumed = gasConsumed.Div(gasConsumed, gasPrice) // division by zero felt is zero felt
```
Comment (hudem1) [inline rpc/v6/simulation.go:131]: so this was the main issue ?

Comment (AnkushinDaniil) [reply rpc/v6/simulation.go:131]: Yes

**Review by hudem1 — APPROVED** [review]
There is just an e2e test that fails (starknet-rs)
