### PR TITLE
Remove errorpkg and replace with Logger

### LINKED ISSUE #277: Remove errpkg from all
We currently have the log package, and an old errpkg to handle exceptions.

We should remove errpkg from where it is used and replace with the Logger.

### PR DESCRIPTION
**Pull request by D-DePablos**
Fixes | Closes | Resolves #277 

Removes errpkg in favour of new Logger. Replaces all calls to CheckFatal to Logger.Fatal

### CODE REVIEW

File: cmd/juno-cli/cli/root.go [hunk 1]
```diff
@@ -121,12 +120,16 @@ func initConfig() error {
 		}
 		viper.SetConfigFile(filepath.Join(config.Dir, "juno.yaml"))
 		err = viper.ReadInConfig()
-		errpkg.CheckFatal(err, "Failed to read in Config after generation.")
+		if err != nil {
+			Logger.With("Error", err).Error("Failed to read config file")
+		}
```
Comment (IronGauntlets) [inline cmd/juno-cli/cli/root.go:125]: This is not equivalent to the behaviour that existed before. Whenever the error package calls check fatal the binary would stop running. However, using `Logger.Error` will not stop the execution of the binary. Therefore you should use `Logger.Fatal/f()` instead.

File: cmd/juno-cli/cli/root.go [hunk 2]
```diff
@@ -121,12 +120,16 @@ func initConfig() error {
...
 	}
 
 	// Unmarshal and log runtime config instance.
 	err = viper.Unmarshal(&config.Runtime)
-	errpkg.CheckFatal(err, "Unable to unmarshal runtime config instance.")
+	if err != nil {
+		Logger.With("Error", err).Error("Failed to unmarshal runtime config")
+	}
```
[the remark this answers is not in the document]
Comment (IronGauntlets) [reply cmd/juno-cli/cli/root.go:132]: Also please use `Fatal`

File: cmd/juno/cli/root.go [hunk 3]
```diff
@@ -188,18 +187,25 @@ func initConfig() {
 		}
 		viper.SetConfigFile(filepath.Join(config.Dir, "juno.yaml"))
 		err = viper.ReadInConfig()
-		errpkg.CheckFatal(err, "Failed to read in Config after generation.")
+		if err != nil {
+			Logger.With("Error", err).Error("Error reading config file")
+		}
```
Comment (IronGauntlets) [inline cmd/juno/cli/root.go:192]: - Please use Fatal
- Please don't use Error in the log message since the logger with print Error word because of the function call to Error. We want the output to be easily readable

File: cmd/juno/cli/root.go [hunk 4]
```diff
@@ -188,18 +187,25 @@ func initConfig() {
...
 	}
 
 	// Unmarshal and log runtime config instance.
 	err = viper.Unmarshal(&config.Runtime)
-	errpkg.CheckFatal(err, "Unable to unmarshal runtime config instance.")
+	if err != nil {
+		Logger.With("Error", err).Error("Error unmarshalling Config instance")
+	}
```
Comment (IronGauntlets) [inline cmd/juno/cli/root.go:199]: See above

File: cmd/juno/cli/root.go [hunk 5]
```diff
@@ -188,18 +187,25 @@ func initConfig() {
...
 
 	// Configure logger - we want the logger to be created right after the config has been set
 	enableJsonOutput := config.Runtime.Logger.EnableJsonOutput
 	verbosityLevel := config.Runtime.Logger.VerbosityLevel
 	err = ReplaceGlobalLogger(enableJsonOutput, verbosityLevel)
-	errpkg.CheckFatal(err, "Failed to initialise logger.")
+	if err != nil {
+		Logger.With("Error", err).Error("Error initialising Logger")
+	}
+
```
Comment (IronGauntlets) [inline cmd/juno/cli/root.go:208]: See above

File: internal/config/config.go [hunk 6]
```diff
@@ -83,11 +82,15 @@ var Runtime *Config
 
 func init() {
 	// Set user config directory.
+	// notest
 	d, err := os.UserConfigDir()
-	errpkg.CheckFatal(err, "Unable to get the user config directory.")
+	if err != nil {
+		Logger.With("Error", err).Error("Could not get user config directory")
+	}
```
Comment (IronGauntlets) [inline internal/config/config.go:89]: Please use `Fatal()`

File: internal/config/config.go [hunk 7]
```diff
@@ -109,7 +112,9 @@ func init() {
 				// Create Juno data directory if it does not exist
 				if _, err := os.Stat(result); errors.Is(err, os.ErrNotExist) {
 					err = os.MkdirAll(result, 0o744)
-					errpkg.CheckFatal(err, "Unable to create user data directory.")
+					if err != nil {
+						Logger.With("Error", err).Error("Could not create user data directory")
+					}
```
Comment (IronGauntlets) [inline internal/config/config.go:117]: same as above

File: internal/config/config.go [hunk 8]
```diff
@@ -118,7 +123,10 @@ func init() {
 			return "", errors.New("user data directory not found")
 		}
 	}()
-	errpkg.CheckFatal(err, "Unable to get user data directory.")
+	// If there is an error
+	if err != nil {
+		Logger.With("Error", err).Error("Could not get user data directory")
+	}
```
Comment (IronGauntlets) [inline internal/config/config.go:129]: See above

File: internal/config/config.go [hunk 9]
```diff
@@ -129,8 +137,11 @@ func New() {
 	if _, err := os.Stat(Dir); os.IsNotExist(err) {
 		// notest
 		err := os.MkdirAll(Dir, 0o755)
-		errpkg.CheckFatal(err, "Failed to create Config directory.")
+		if err != nil {
+			Logger.With("Error", err).Error("Could not create config directory")
+		}
```
Comment (IronGauntlets) [inline internal/config/config.go:142]: same as above

File: internal/config/config.go [hunk 10]
```diff
@@ -146,12 +157,16 @@ func New() {
 			Network: "mainnet",
 		},
 	})
-	errpkg.CheckFatal(err, "Failed to marshal Config instance to byte data.")
+	if err != nil {
+		Logger.With("Error", err).Error("Could not marshal default config")
+	}
```
Comment (IronGauntlets) [inline internal/config/config.go:162]: same as above

File: internal/config/config.go [hunk 11]
```diff
@@ -146,12 +157,16 @@ func New() {
...
 	// Create default Juno configuration file if it does not exist
 	if _, err := os.Stat(f); errors.Is(err, os.ErrNotExist) {
 		// notest
 		err = os.WriteFile(f, data, 0o644)
-		errpkg.CheckFatal(err, "Failed to write config file.")
+		if err != nil {
+			Logger.With("Error", err).Error("Could not create default config file")
+		}
```
Comment (IronGauntlets) [inline internal/config/config.go:169]: same as above

File: pkg/feeder/feeder.go [hunk 12]
```diff
@@ -32,8 +31,11 @@ type Client struct {
 
 // NewClient returns a new Client.
 func NewClient(baseURL, baseAPI string, client *HttpClient) *Client {
+	// notest
 	u, err := url.Parse(baseURL)
-	errpkg.CheckFatal(err, "Bad base URL.")
+	if err != nil {
+		Logger.With("Error", err).Error("Unable to parse base URL")
+	}
```
Comment (IronGauntlets) [inline pkg/feeder/feeder.go:38]: same as above

**Review by stdevMac — APPROVED** [review]

File: cmd/juno-cli/cli/root.go [hunk 13]
```diff
@@ -141,6 +144,6 @@ func initClient() *feeder.Client {
 // Execute handle flags for Cobra execution.
 func Execute() {
 	if err := rootCmd.Execute(); err != nil {
-		Logger.With("Error", err).Error("Failed to execute CLI.")
+		Logger.Fatal("Failed to execute Juno.")
```
Comment (tshakalekholoane) [inline cmd/juno-cli/cli/root.go:147]: Since Juno is somewhat monolithic, I think it pays to be specific about which part failed to run, here the CLI.

File: internal/config/config.go [hunk 14]
```diff
@@ -83,11 +82,15 @@ var Runtime *Config
 
 func init() {
 	// Set user config directory.
+	// notest
 	d, err := os.UserConfigDir()
-	errpkg.CheckFatal(err, "Unable to get the user config directory.")
+	if err != nil {
+		Logger.Fatal("Could not get retrieve Juno config directory.")
```
Comment (tshakalekholoane) [inline internal/config/config.go:88]: Typo. "Could not ~~get~~ retrieve Juno config directory.". I'd also remove the word "Juno" as well.

**Review by tshakalekholoane — CHANGES_REQUESTED** [review]

**Review by tshakalekholoane — APPROVED** [review]

**Review by IronGauntlets — APPROVED** [review]
